### ISSUE TITLE
What are these environment variables ?

### ISSUE THREAD

**Issue by shibakar** [minhng92/odoo-17-docker-compose#7]
<img width="318" alt="Screenshot 2024-03-21 at 10 03 44 AM" src="https://github.com/minhng92/odoo-17-docker-compose/assets/96728481/a6cb8a69-7b06-4e97-90b2-1841574f7575">

**Comment by minhng92** [comment]
Hi @shibakar,

These variables pertain to the connection information for the Postgres database.

HOST represents the hostname for connection, analogous to the Docker service name.
USER and PASSWORD correspond to the Postgres user credentials.

**Comment by shibakar** [comment]
@minhng92  how can I change the password of ```odoo17@2023``` I have already added a db management tool 

```yml
 pgadmin:
    image: dpage/pgadmin4
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=xxxxxxxxxxx
      - PGADMIN_DEFAULT_PASSWORD=xxxxxxxx
    ports:
      - "5050:80"
    restart: always   
```
